name: auth_repository
description: auth_repository

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.0
  intl: ^0.17.0
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.4.0
  uuid: ^3.0.6
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_lints: ^2.0.0

