name: shared_notes
description: Shared Notes
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flow_builder: ^0.0.9
  introduction_screen: ^3.1.8
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  google_fonts: ^4.0.3
  get: ^4.6.5
  curved_labeled_navigation_bar: ^2.0.2
  utils:
    path: packages/utils
  firestore_repository:
    path: packages/firestore_repository
  auth_repository:
    path: packages/auth_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
