// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCVf4HhYbDsfQsxp8zCzmBb0cvtCGcRsM',
    appId: '1:301881152319:web:8e01b23c78f0579997b98a',
    messagingSenderId: '301881152319',
    projectId: 'shared-notes-dev',
    authDomain: 'shared-notes-dev.firebaseapp.com',
    storageBucket: 'shared-notes-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1iIxNyT58hT5l1f7up7wUg7L1PO0g3I',
    appId: '1:301881152319:android:9484b701d20e375197b98a',
    messagingSenderId: '301881152319',
    projectId: 'shared-notes-dev',
    storageBucket: 'shared-notes-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFgto5s3yDfcwjG_c4VAJVHW58U_6VuGw',
    appId: '1:301881152319:ios:2a2b5d1c3155f83b97b98a',
    messagingSenderId: '301881152319',
    projectId: 'shared-notes-dev',
    storageBucket: 'shared-notes-dev.appspot.com',
    iosClientId: '301881152319-t083c1hbbnh5le921eldqteho13abkd4.apps.googleusercontent.com',
    iosBundleId: 'com.ortexsoft.sharedNotes',
  );
}
