name: utils
description: utils

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0

